filebeat.inputs:
- type: syslog
  enabled: true
  protocol.udp:
    host: "*:5014" # IP:Port of host receiving syslog traffic
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 3
setup.dashboards.enabled: true
setup.kibana:
  host: "localhost:5601"
  ssl.enabled: false
  username: elastic
  password: changeme
output.logstash:
  hosts: ["localhost:5044"]
  timeout: 300
  ssl.enabled: false
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

